name: cicd

on:
 push:
   branches: [dev]
 pull_request:
   branches: [dev]

jobs:
  frontend:
   runs-on: ubuntu-22.04

   steps:
     - name: first
       run: echo "hello world"
  backend:
    runs-on: windows-2022

    steps:
      - name: second
        run : echo "hello from second"
