name: new_pipeline

on:
 push:
   branches: [main]
 pull_request:
   branches: [main]

jobs:
  build:
   runs-on: windows-latest
   steps:
     - name: first
       uses: actions/checkout@v4

     - name: second
       run: |
        echo "installing dependenices"
        npm i 

     - name: third
       run:  echo "working"
     
        
